### ISSUE TITLE
Automize Dingo file download from Zenodo for example.py

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#10]
Provide an automized Dingo file download from a specific dataset version uploaded to Zenodo. If the given file is not available on somebody's disc, download it from Zenodo.

## Todos

- [ ] Run Dingo again and upload single .pkl files to Zenodo
- [x] Use requests package to download MV Grid 3545 data
- [x] Create data/ directory within example.py script
- [ ] Throw an Error if the file is not available
- [ ] Once implemented, add example of `import_from_dingo()` to `Network`'s docstring

**Comment by gplssm** [comment]
Outdated
