### ISSUE TITLE
Obtain the power_class of the wind onshore for the correct feedin

### ISSUE THREAD

**Issue by boltbeard** [openego/eDisGo#121]
With the change in the renewable feedin time series from oedb from using `model_draft.ego_simple_feedin` to `model_draft.ego_renewable_feedin_v031` it introduces the usage of `weather_cell_id` for assigning the feedin time series. 

In addition to the `weather_cell_id` in `model_draft.ego_renewable_feedin_v031`, there is a `power_class` for `wind_onshore` that has also been introduced. For further information, please refer to https://github.com/openego/data_processing/issues/231 and https://github.com/openego/data_processing/issues/235. Currently there are 8 `power_classes` where 1-7 denote different power classes or onshore wind generators and 0 is used for other technologies. Typically a power class is assigned to every entry in `model_draft.ego_supply_pf_generator_single` and a reference turbine is used for getting the setting and parameters for further calculation.

Currently this information per generator isn't available to ding0 and hence unavilable to eDisGo. The assumption made till this can be included in ding0 and eventually eDisGo is that all `wind_onshore` have the `power_class` 4. This is used where information isn't available (information about foreign turbines). The validity of this assumption could be questioned and I am open to suggestion about a different assumption (like maybe using the average of all `power_classes` instead).

Update 2018-07-25
=================
After having a closer look at the power_class implementations in eTraGo and its working within eGo in combination with eDisGo, the following conclusions were made:

1. The major use case of eDisGo is to be used in conjunction with eTraGo as part of the entire eGo tool suite, where active power timeseries in eTraGo would be calculated by considering the power classes in the aggregated generators, and provide an averaged time series curve per technology per weather cell  to eDisGo for each technology for each weather cell. (This is the current state of the implementation)

2. The current state of the implementation does induce inacurracies due to the averaging of all the time series of all the generators at an mv grid and weather cell (grouper is 'carrier', hvmv bus and weather cell). It is currently assumed that this induced inaccuracy is acceptable until quantifiable evidence proves it to be otherwise. Although this has not been quantified yet, there are methods that this can be done

The reasoning for the acceptance for of the induced inaccuracy is:
- The impact of the averaging affects only the peaks (feedin/load) in extreme cases by reducing them. The energy does not change.
- The errors in the assumptions of the individual generator's power classes gets diffused by this. For example the power classes assigned to wind parks with multiple types of wind turbines would take the oldest power class even if the wind park was expanded with other types of wind turbines.

It is generally acknowledged that there are strong arguments to have these assumptions validated.

For the case where eDisGo is run Independently, as mentioned above, the `power_class` 4 is used. Maybe a better assumptions could be made with further evaluation of which assumption may be "more" valid based upon the sized of wind generators usually connected to the medium voltage levels.

**Comment by boltbeard** [comment]
> ### Information needed and Decisions to make
> 1. How are power classes dealt with in eTraGo? It would be good to handle them similarly in eDisGo for consistency.
> 2. Is there a generalization if the power_class attribute is absent in the generator?
> 3. How wrong/right would any analysis be by assuming a power_class of 4 for all wind generators as handled in eDisGo (issue #121)? 
> 4. What is the priority of this Task?

These questions from ding0 issue [#225](https://github.com/openego/ding0/issues/255) need to be answered

### Tasks to include and use `power_class`

- [ ] Fix ding0 issue [#225](https://github.com/openego/ding0/issues/255)
- [ ] Introduce a `power_class` attribute in [GeneratorFluctuating](https://github.com/openego/eDisGo/blob/dev/edisgo/grid/components.py#L398-L557) Class in eDisGo
- [ ] Modify the function (_retrieve_timeseries_from_oedb)[https://github.com/openego/eDisGo/blob/dev/edisgo/data/import_data.py#L1997-L2062] to take in the `power_class` also as an input an get the correct corresponding time series for each generator
- [ ] Documentation of the change

**Comment by MarlonSchlemminger** [comment]
> How are power classes dealt with in eTraGo? It would be good to handle them similarly in eDisGo for consistency.

Power classes don't appear directly in eTraGo at all, only in the dataprocessing. How power classes work is documented [here](https://github.com/openego/data_processing/issues/231). A code example of how they are used can be found [here](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_generator.sql#L265-L281). I am not sure if I answered your question, please be more specific if I didn't.

> Is there a generalization if the power_class attribute is absent in the generator?

Not sure again if I understand your question correctly. The power class can only be absent if the generator has no maximum power output assigned, which should never be the case, right?

> How wrong/right would any analysis be by assuming a power_class of 4 for all wind generators as handled in eDisGo (issue #121)?

I never evaluated that. A first try could be to compare the power curves of the turbines used, which can be found [here](https://github.com/wind-python/windpowerlib/blob/dev/windpowerlib/data/power_curves.csv). I don't know how different they are. From a hub height and rotor diamater perspective, power class 4 looks like a good average.

**Comment by boltbeard** [comment]
> Power classes don't appear directly in eTraGo at all, only in the dataprocessing. How power classes work is documented here. A code example of how they are used can be found here. I am not sure if I answered your question, please be more specific if I didn't.

Thank you for the clarification, I was referring to How eTraGo obtains the feedin time series using the `power_class` through `ego_renewable_feedin` for their calculations.

> Not sure again if I understand your question correctly. The power class can only be absent if the generator has no maximum power output assigned, which should never be the case, right?

> ...

> I never evaluated that. A first try could be to compare the power curves of the turbines used, which can be found here. I don't know how different they are. From a hub height and rotor diamater perspective, power class 4 looks like a good average.

One the same note from the clarification above, from the feedin time series and calculation perspective, if the `power_class` information is inaccessible (from eDisGo for example) then what generalization can I use to still get a feedin time series that isn't extremely wrong (a good assumption till the `power_class` is correctly accessible from eDisGo).

**Comment by MarlonSchlemminger** [comment]
> Thank you for the clarification, I was referring to How eTraGo obtains the feedin time series using the power_class through ego_renewable_feedin for their calculations.

The table `ego_renewable_feedin` stores feedin timeseries for each CoastDat2 weather cell and each power class. Each generator gets assigned a weather cell ID (depending on its location) and a power class (depending on its nominal capacity) as well. After that, it is an easy match, assign a time series to each generator where power class and weather cell ID are equal. This is done [here](https://github.com/openego/data_processing/blob/dev/dataprocessing/sql_snippets/ego_dp_powerflow_timeseries_generator.sql#L70-L120).

> One the same note from the clarification above, from the feedin time series and calculation perspective, if the power_class information is inaccessible (from eDisGo for example) then what generalization can I use to still get a feedin time series that isn't extremely wrong (a good assumption till the power_class is correctly accessible from eDisGo).

Why isn't the power class available currently in eDisGo? As I said, all you need to assign a power class to each generator is its nominal capacity, which I assume is a really basic information that should be available. If it somehow is not available, you could do what I suggested in my last comment and evaluate the power curves from [the windlib](https://github.com/wind-python/windpowerlib/blob/dev/windpowerlib/data/power_curves.csv) for all 7 onshore turbines used and see how much of a difference there is. I would assume that the difference between them isn't too big and power class 4 is probably a good average in terms of hub height and rotor diameter.

**Comment by boltbeard** [comment]
> Why isn't the power class available currently in eDisGo? 

This was only recently made relevant after https://github.com/openego/data_processing/issues/235 was raised, before that eDisGo queried its time series from something like a test table called `ego_simple_feedin` in `model_draft`. This was fixed in #86 and #122.

> As I said, all you need to assign a power class to each generator is its nominal capacity, which I assume is a really basic information that should be available. 

We are still working on it... it can be made available only through ding0

> If it somehow is not available, you could do what I suggested in my last comment and evaluate the power curves from the windlib for all 7 onshore turbines used and see how much of a difference there is. I would assume that the difference between them isn't too big and power class 4 is probably a good average in terms of hub height and rotor diameter.

This already gives me some insight to evaluate the correctness of the assumption, thank you for that.

**Comment by boltbeard** [comment]
### Update 2018-07-25

After having a closer look at the power_class implementations in eTraGo and its working within eGo in combination with eDisGo, the following conclusions were made:

1. The major use case of eDisGo is to be used in conjunction with eTraGo as part of the entire eGo tool suite, where active power timeseries in eTraGo would be calculated by considering the power classes in the aggregated generators, and provide an averaged time series curve per technology per weather cell  to eDisGo for each technology for each weather cell. (This is the current state of the implementation)

2. The current state of the implementation does induce inacurracies due to the averaging of all the time series of all the generators at an mv grid. It is currently assumed that this induced inaccuracy is acceptable until quantifiable evidence proves it to be otherwise. Although this has not been quantified yet, there are methods that this can be done

The reasoning for the acceptance for of the induced inaccuracy is:
- The impact of the averaging affects only the peaks (feedin/load) in extreme cases by reducing them. The energy does not change.
- The errors in the assumptions of the individual generator's power classes gets diffused by this. For example the power classes assigned to wind parks with multiple types of wind turbines would take the oldest power class even if the wind park was expanded with other types of wind turbines.

It is generally acknowledged that there are strong arguments to have these assumptions validated.

For the case where eDisGo is run Independently, as mentioned above, the `power_class` 4 is used. Maybe a better assumptions could be made with further evaluation of which assumption may be "more" valid based upon the sized of wind generators usually connected to the medium voltage levels.

**Comment by birgits** [comment]
Can we close this or should we leave it open as a reminder? I would then change Milestone, Labels and Assignees.

**Comment by boltbeard** [comment]
I'd say it would be good to leave it open and change the Milestones, Labels and Assignees.
