### ISSUE TITLE
Provide flexible eDisGo pooling function

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#130]
Function in this context refers to the pooling function shall be able to run with any eDisGo applying function. Therefore, inputs and outputs are defined as follows

*Input*
- the function to be parallelized
- argument tuple (or suitable data structure)

*Output*
Either: dict of EDisGo instances with the format {'mvgd_id': EDisGo()} (preferred!)
Or: list of EDisGo instances

For inspiration see [the current pool function](https://github.com/openego/eDisGo/blob/8e591cbc9e2d2efcb5b9f90fde176c51de2f3646/edisgo/tools/edisgo_run.py#L225-#L279) that has the drawback of being limited to parallelize a particular function (in this case run_edisgo_twice())

### Tasks

- [x] change collect_pool_results() to return dict
- [x] change func_arguments to take tuple directly
- [x] Decide if list of IDs shall be passed separately from functions arguments
- [x] Apdat return of flexible pooling function
- [x] Update docs (usage/quickstart)
- [x] Update "What's New"
