### ISSUE TITLE
Importer for Dingo grid data

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#2]
**Questions**
* Don't we want to lists like __loads_, __generators_ etc. as attribute of Grid. **Answer** check if the nodes can be categorized with the help of nx and if lists could be build from that **Answer2** Yepp, is possible and implemented :smile: 
* Currently I'm using the plain `nx.Graph.add_node() ` method to i.e. add a load to eDisGo data structure. There is no check if this node already exists nor if it is of the appropriate type. Any objections @nesnoj ?
* Where do we get the sectoral consumption of loads from? Dingo load object only have the attribute `peak_load` with no sector specification **Answer** We need to know the sectoral share: see Dingo Issue
* Do we first assign the capacity/peak_load  from dingo data to newly created objects and override it later when i.e. generators are imported or do we simply left it unassigned on data import?
* Attribute _mv_disconn_points at MVGrid is not needed -> nodes with attributes

**TODOs before close**
- [x] Assign line type to lines of aggregated generators and loads
- [x] Check-up used classes with UML
- [x] Check documentation
- [x] Validate resulting grid data (_fill with ideas for validation, @nesnoj as well_)
  - [x] Number of nodes equivalent to Dingo data
  - [x] Number of LV edges equivalent to Dingo data
  ~~- [ ] Number of MV edges equivalent to Dingo data~~ in favor of #11 
  - [x] Cumulative sectoral load
  - [x] Cumulative generation capacity

**Comment by gplssm** [comment]
Behandlung aggregierter LAs
* Weiteres Attribut an mv_grid: aggregates mit [{'population': value1, 'geom': value2}]
* Aggregation der Last und Erzeugung (diese nach subtype) mit 1m Kabellänge an der MV Station angeschl.
* Implikationen für Implementierung
** Sonderbehandlung von LV grid districts, die sich in aggr. LA befinden
* Weiterhin soll ermöglicht werden ganze LV grids aggregiert abzubilden

**Comment by gplssm** [comment]
MV part is implemented. Validation of data works for some grid components: branch_tee,                      disconnection_point, mv_transformer, lv_station. Lines, generators and load are not included yet.
* Lines: unequal number outside aggregated LA in Dingo/ eDisGo. @nesnoj I need a smoe to discuss, at least virtually!
* Generators: can't be compared via number of generators. Will be compared on the basis of cumulative capacity per technology for MV and LV (once, LV is implemented)
* Loads will be compared accordingly to generators
