### ISSUE TITLE
Equip Storage() with a storage model

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#9]
* Must match the storage model in eTraGo
* Should be ready for advanced storage models
* Should meet M5BAT2 and openBEA needs

**Comment by gplssm** [comment]
First, a simple storage integration will be implemented. It considers the case of combined analysis with eTraGo. The storage is placed at the secondary side of the HV/MV substation. Its operational time series derive from operation determined by eTraGo.

**Tasks**

- [ ] Extend class `Storage`
- [x] Provide `StorageOperation` class
- [ ] `StorageOperation` to `Storage`: return time series from `StorageOperation.timeseries` when `Storage.operation` is not `None`
- [ ] Add storage to `to_pypsa()` converter: component and time series
- [ ] Provide function `integrate_storage()` to place storages in the grid. First, only one method is available `storage_at_hvmv_substation()`
- [ ] Test dry-run implementation and adapt to data
  - [ ] Adapt data conversion in  `StorageOperation.define_timeseries` once eTraGo data is available

This issue considers storage integration in the eDisGo data structure too, which is requested by #8.

**Comment by gplssm** [comment]
Currently, only available in features/storage-integration2
